name: Build frontend

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: |
          cd frontend
          npm install
          npm run build
