name: Build frontend

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
          with:
            node-version: 14.x
      - name: run npm install and build
        run: |
          cd frontend
          npm install
          npm run build
